/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type CreatorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "creator";
};

export type FavoriteCreator = {
  _type: "favoriteCreator";
  onSite?: CreatorReference;
  name?: string;
  url?: string;
};

export type SocialLink = {
  _type: "socialLink";
  platform:
    "Instagram" | "X" | "Bluesky" | "TikTok" | "YouTube" | "Website" | "Other";
  url: string;
};

export type BuyLink = {
  _type: "buyLink";
  store:
    | "Own store"
    | "Bookshop.org"
    | "Amazon"
    | "Gumroad"
    | "Etsy"
    | "Kickstarter"
    | "Other";
  url: string;
};

export type BookReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "book";
};

export type ColumnReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "column";
};

export type InterviewReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "interview";
};

export type HomepageFeature = {
  _id: string;
  _type: "homepageFeature";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  active?: boolean;
  order?: number;
  items?: ArrayOf<
    BookReference | CreatorReference | ColumnReference | InterviewReference
  >;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type FreeDownload = {
  _id: string;
  _type: "freeDownload";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  creator: CreatorReference;
  description?: string;
  cover?: ImageWithAlt;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  publishedAt?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Interview = {
  _id: string;
  _type: "interview";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  interviewer: CreatorReference;
  subject: CreatorReference;
  excerpt?: string;
  cover?: ImageWithAlt;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageWithAlt)
  >;
  publishedAt: string;
};

export type Column = {
  _id: string;
  _type: "column";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  author: CreatorReference;
  excerpt?: string;
  cover?: ImageWithAlt;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & ImageWithAlt)
  >;
  publishedAt: string;
};

export type Book = {
  _id: string;
  _type: "book";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  creator: CreatorReference;
  cover?: ImageWithAlt;
  genres?: Array<
    | "Action & Adventure"
    | "Sci-Fi"
    | "Fantasy"
    | "Horror"
    | "Crime & Noir"
    | "Romance"
    | "Drama"
    | "Slice of Life"
    | "Historical"
    | "Superhero"
    | "Humor & Satire"
    | "Memoir & Autobio"
    | "Queer"
    | "Weird & Experimental"
    | "Punk & Protest"
  >;
  format?:
    | "Graphic Novel"
    | "Single Issue"
    | "Collected Edition"
    | "Anthology"
    | "Minicomic"
    | "Zine"
    | "Webcomic";
  maturity?: "All Ages" | "Teen" | "Teen+" | "Mature";
  status?: "Ongoing" | "Complete" | "Upcoming";
  shortDescription?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  buyLinks?: Array<
    {
      _key: string;
    } & BuyLink
  >;
  kickstarterUrl?: string;
};

export type OrganizationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "organization";
};

export type Creator = {
  _id: string;
  _type: "creator";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  studio?: OrganizationReference;
  organizations?: Array<
    {
      _key: string;
    } & OrganizationReference
  >;
  genres?: Array<
    | "Action & Adventure"
    | "Sci-Fi"
    | "Fantasy"
    | "Horror"
    | "Crime & Noir"
    | "Romance"
    | "Drama"
    | "Slice of Life"
    | "Historical"
    | "Superhero"
    | "Humor & Satire"
    | "Memoir & Autobio"
    | "Queer"
    | "Weird & Experimental"
    | "Punk & Protest"
  >;
  formats?: Array<
    | "Graphic Novel"
    | "Single Issue"
    | "Collected Edition"
    | "Anthology"
    | "Minicomic"
    | "Zine"
    | "Webcomic"
  >;
  audience?: "All Ages" | "Teen" | "Teen+" | "Mature";
  openToCollaboration?: boolean;
  photo?: ImageWithAlt;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  location?: string;
  website?: string;
  socials?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  favoriteCreators?: Array<
    {
      _key: string;
    } & FavoriteCreator
  >;
};

export type Organization = {
  _id: string;
  _type: "organization";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  website?: string;
  logo?: ImageWithAlt;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle: string;
  siteDescription?: string;
  footer?: string;
  hero?: {
    background?: ImageWithAlt;
    headline?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    featureCtaLabel?: string;
    ctas?: Array<{
      label: string;
      href: string;
      _type: "cta";
      _key: string;
    }>;
  };
  home?: {
    genresHeading?: string;
    booksHeading?: string;
    creatorsHeading?: string;
    viewAllLabel?: string;
  };
  sections?: {
    editorialHeading?: string;
    columnsHeading?: string;
    interviewsHeading?: string;
    booksHeading?: string;
    creatorsHeading?: string;
    downloadsHeading?: string;
    genreBooksHeading?: string;
    genreCreatorsHeading?: string;
    downloadCta?: string;
    kickstarterCta?: string;
    creatorBooksHeading?: string;
    creatorOrganizationsHeading?: string;
    openToCollaborationLabel?: string;
    creatorFavoritesHeading?: string;
  };
  empty?: {
    books?: string;
    creators?: string;
    genreBooks?: string;
    genreCreators?: string;
    columns?: string;
    interviews?: string;
    downloads?: string;
  };
  join?: {
    heading?: string;
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: null;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    ctaLabel?: string;
    formUrl?: string;
  };
  nav?: Array<{
    label: string;
    href: string;
    _type: "navItem";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ImageWithAlt
  | CreatorReference
  | FavoriteCreator
  | SocialLink
  | BuyLink
  | BookReference
  | ColumnReference
  | InterviewReference
  | HomepageFeature
  | SanityFileAssetReference
  | FreeDownload
  | Slug
  | Interview
  | Column
  | Book
  | OrganizationReference
  | Creator
  | Organization
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/queries.ts
// Variable: CREATORS_QUERY
// Query: *[_type=="creator"]|order(name asc){_id,name,"slug":slug.current,location,photo,genres,openToCollaboration,studio->{_id,name,"slug":slug.current,website,logo}}
export type CREATORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  location: string | null;
  photo: ImageWithAlt | null;
  genres: Array<
    | "Action & Adventure"
    | "Crime & Noir"
    | "Drama"
    | "Fantasy"
    | "Historical"
    | "Horror"
    | "Humor & Satire"
    | "Memoir & Autobio"
    | "Punk & Protest"
    | "Queer"
    | "Romance"
    | "Sci-Fi"
    | "Slice of Life"
    | "Superhero"
    | "Weird & Experimental"
  > | null;
  openToCollaboration: boolean | null;
  studio: {
    _id: string;
    name: string;
    slug: string;
    website: string | null;
    logo: ImageWithAlt | null;
  } | null;
}>;

// Source: src/lib/queries.ts
// Variable: CREATOR_QUERY
// Query: *[_type=="creator" && slug.current==$slug][0]{  _id,name,location,website,bio,photo,socials,openToCollaboration,genres,formats,audience,  studio->{_id,name,"slug":slug.current,website,logo},  organizations[]->{_id,name,"slug":slug.current,website,logo},  favoriteCreators[]{name,url,"onSiteName":onSite->name,"onSiteSlug":onSite->slug.current},  "books": *[_type=="book" && references(^._id)]|order(title asc){_id,title,"slug":slug.current,status,genres,format,maturity,cover,"creatorName":creator->name}}
export type CREATOR_QUERY_RESULT = {
  _id: string;
  name: string;
  location: string | null;
  website: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  photo: ImageWithAlt | null;
  socials: Array<
    {
      _key: string;
    } & SocialLink
  > | null;
  openToCollaboration: boolean | null;
  genres: Array<
    | "Action & Adventure"
    | "Crime & Noir"
    | "Drama"
    | "Fantasy"
    | "Historical"
    | "Horror"
    | "Humor & Satire"
    | "Memoir & Autobio"
    | "Punk & Protest"
    | "Queer"
    | "Romance"
    | "Sci-Fi"
    | "Slice of Life"
    | "Superhero"
    | "Weird & Experimental"
  > | null;
  formats: Array<
    | "Anthology"
    | "Collected Edition"
    | "Graphic Novel"
    | "Minicomic"
    | "Single Issue"
    | "Webcomic"
    | "Zine"
  > | null;
  audience: "All Ages" | "Mature" | "Teen" | "Teen+" | null;
  studio: {
    _id: string;
    name: string;
    slug: string;
    website: string | null;
    logo: ImageWithAlt | null;
  } | null;
  organizations: Array<{
    _id: string;
    name: string;
    slug: string;
    website: string | null;
    logo: ImageWithAlt | null;
  }> | null;
  favoriteCreators: Array<{
    name: string | null;
    url: string | null;
    onSiteName: string | null;
    onSiteSlug: string | null;
  }> | null;
  books: Array<{
    _id: string;
    title: string;
    slug: string;
    status: "Complete" | "Ongoing" | "Upcoming" | null;
    genres: Array<
      | "Action & Adventure"
      | "Crime & Noir"
      | "Drama"
      | "Fantasy"
      | "Historical"
      | "Horror"
      | "Humor & Satire"
      | "Memoir & Autobio"
      | "Punk & Protest"
      | "Queer"
      | "Romance"
      | "Sci-Fi"
      | "Slice of Life"
      | "Superhero"
      | "Weird & Experimental"
    > | null;
    format:
      | "Anthology"
      | "Collected Edition"
      | "Graphic Novel"
      | "Minicomic"
      | "Single Issue"
      | "Webcomic"
      | "Zine"
      | null;
    maturity: "All Ages" | "Mature" | "Teen" | "Teen+" | null;
    cover: ImageWithAlt | null;
    creatorName: string;
  }>;
} | null;

// Source: src/lib/queries.ts
// Variable: BOOKS_QUERY
// Query: *[_type=="book"]|order(title asc){_id,title,"slug":slug.current,status,genres,format,maturity,cover,"creatorName":creator->name}
export type BOOKS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  status: "Complete" | "Ongoing" | "Upcoming" | null;
  genres: Array<
    | "Action & Adventure"
    | "Crime & Noir"
    | "Drama"
    | "Fantasy"
    | "Historical"
    | "Horror"
    | "Humor & Satire"
    | "Memoir & Autobio"
    | "Punk & Protest"
    | "Queer"
    | "Romance"
    | "Sci-Fi"
    | "Slice of Life"
    | "Superhero"
    | "Weird & Experimental"
  > | null;
  format:
    | "Anthology"
    | "Collected Edition"
    | "Graphic Novel"
    | "Minicomic"
    | "Single Issue"
    | "Webcomic"
    | "Zine"
    | null;
  maturity: "All Ages" | "Mature" | "Teen" | "Teen+" | null;
  cover: ImageWithAlt | null;
  creatorName: string;
}>;

// Source: src/lib/queries.ts
// Variable: BOOK_QUERY
// Query: *[_type=="book" && slug.current==$slug][0]{  _id,title,status,genres,format,maturity,description,buyLinks,kickstarterUrl,cover,  "creatorName":creator->name,"creatorSlug":creator->slug.current}
export type BOOK_QUERY_RESULT = {
  _id: string;
  title: string;
  status: "Complete" | "Ongoing" | "Upcoming" | null;
  genres: Array<
    | "Action & Adventure"
    | "Crime & Noir"
    | "Drama"
    | "Fantasy"
    | "Historical"
    | "Horror"
    | "Humor & Satire"
    | "Memoir & Autobio"
    | "Punk & Protest"
    | "Queer"
    | "Romance"
    | "Sci-Fi"
    | "Slice of Life"
    | "Superhero"
    | "Weird & Experimental"
  > | null;
  format:
    | "Anthology"
    | "Collected Edition"
    | "Graphic Novel"
    | "Minicomic"
    | "Single Issue"
    | "Webcomic"
    | "Zine"
    | null;
  maturity: "All Ages" | "Mature" | "Teen" | "Teen+" | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  buyLinks: Array<
    {
      _key: string;
    } & BuyLink
  > | null;
  kickstarterUrl: string | null;
  cover: ImageWithAlt | null;
  creatorName: string;
  creatorSlug: string;
} | null;

// Source: src/lib/queries.ts
// Variable: GENRES_QUERY
// Query: array::unique(*[_type=="book" && defined(genres)].genres[])
export type GENRES_QUERY_RESULT = Array<
  | "Action & Adventure"
  | "Crime & Noir"
  | "Drama"
  | "Fantasy"
  | "Historical"
  | "Horror"
  | "Humor & Satire"
  | "Memoir & Autobio"
  | "Punk & Protest"
  | "Queer"
  | "Romance"
  | "Sci-Fi"
  | "Slice of Life"
  | "Superhero"
  | "Weird & Experimental"
>;

// Source: src/lib/queries.ts
// Variable: GENRE_BOOKS_QUERY
// Query: *[_type=="book" && $genre in genres]|order(title asc){_id,title,"slug":slug.current,status,genres,format,maturity,cover,"creatorName":creator->name}
export type GENRE_BOOKS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  status: "Complete" | "Ongoing" | "Upcoming" | null;
  genres: Array<
    | "Action & Adventure"
    | "Crime & Noir"
    | "Drama"
    | "Fantasy"
    | "Historical"
    | "Horror"
    | "Humor & Satire"
    | "Memoir & Autobio"
    | "Punk & Protest"
    | "Queer"
    | "Romance"
    | "Sci-Fi"
    | "Slice of Life"
    | "Superhero"
    | "Weird & Experimental"
  > | null;
  format:
    | "Anthology"
    | "Collected Edition"
    | "Graphic Novel"
    | "Minicomic"
    | "Single Issue"
    | "Webcomic"
    | "Zine"
    | null;
  maturity: "All Ages" | "Mature" | "Teen" | "Teen+" | null;
  cover: ImageWithAlt | null;
  creatorName: string;
}>;

// Source: src/lib/queries.ts
// Variable: COLUMNS_QUERY
// Query: *[_type=="column"]|order(publishedAt desc){_id,title,"slug":slug.current,excerpt,cover,publishedAt,"authorName":author->name}
export type COLUMNS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  cover: ImageWithAlt | null;
  publishedAt: string;
  authorName: string;
}>;

// Source: src/lib/queries.ts
// Variable: COLUMN_QUERY
// Query: *[_type=="column" && slug.current==$slug][0]{_id,title,body,publishedAt,cover,"authorName":author->name}
export type COLUMN_QUERY_RESULT = {
  _id: string;
  title: string;
  body: Array<
    | ({
        _key: string;
      } & ImageWithAlt)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
  > | null;
  publishedAt: string;
  cover: ImageWithAlt | null;
  authorName: string;
} | null;

// Source: src/lib/queries.ts
// Variable: INTERVIEWS_QUERY
// Query: *[_type=="interview"]|order(publishedAt desc){_id,title,"slug":slug.current,excerpt,cover,publishedAt,"interviewerName":interviewer->name,"subjectName":subject->name}
export type INTERVIEWS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  cover: ImageWithAlt | null;
  publishedAt: string;
  interviewerName: string;
  subjectName: string;
}>;

// Source: src/lib/queries.ts
// Variable: INTERVIEW_QUERY
// Query: *[_type=="interview" && slug.current==$slug][0]{_id,title,body,publishedAt,cover,"interviewerName":interviewer->name,"subjectName":subject->name}
export type INTERVIEW_QUERY_RESULT = {
  _id: string;
  title: string;
  body: Array<
    | ({
        _key: string;
      } & ImageWithAlt)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
  > | null;
  publishedAt: string;
  cover: ImageWithAlt | null;
  interviewerName: string;
  subjectName: string;
} | null;

// Source: src/lib/queries.ts
// Variable: DOWNLOADS_QUERY
// Query: *[_type=="freeDownload"]|order(publishedAt desc){_id,title,"slug":slug.current,description,cover,publishedAt,"creatorName":creator->name}
export type DOWNLOADS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  cover: ImageWithAlt | null;
  publishedAt: string | null;
  creatorName: string;
}>;

// Source: src/lib/queries.ts
// Variable: DOWNLOAD_QUERY
// Query: *[_type=="freeDownload" && slug.current==$slug][0]{_id,title,description,cover,"creatorName":creator->name,"fileUrl":file.asset->url}
export type DOWNLOAD_QUERY_RESULT = {
  _id: string;
  title: string;
  description: string | null;
  cover: ImageWithAlt | null;
  creatorName: string;
  fileUrl: string | null;
} | null;

// Source: src/lib/queries.ts
// Variable: FEATURES_QUERY
// Query: *[_type=="homepageFeature" && active==true]|order(order asc)[0].items[]->{  _type,_id,title,name,"slug":slug.current,cover,photo,genres,format,maturity,  shortDescription,excerpt,location,  "creatorName":creator->name,  "studioName":studio->name}
export type FEATURES_QUERY_RESULT = Array<
  | {
      _type: "book";
      _id: string;
      title: string;
      name: null;
      slug: string;
      cover: ImageWithAlt | null;
      photo: null;
      genres: Array<
        | "Action & Adventure"
        | "Crime & Noir"
        | "Drama"
        | "Fantasy"
        | "Historical"
        | "Horror"
        | "Humor & Satire"
        | "Memoir & Autobio"
        | "Punk & Protest"
        | "Queer"
        | "Romance"
        | "Sci-Fi"
        | "Slice of Life"
        | "Superhero"
        | "Weird & Experimental"
      > | null;
      format:
        | "Anthology"
        | "Collected Edition"
        | "Graphic Novel"
        | "Minicomic"
        | "Single Issue"
        | "Webcomic"
        | "Zine"
        | null;
      maturity: "All Ages" | "Mature" | "Teen" | "Teen+" | null;
      shortDescription: string | null;
      excerpt: null;
      location: null;
      creatorName: string;
      studioName: null;
    }
  | {
      _type: "column";
      _id: string;
      title: string;
      name: null;
      slug: string;
      cover: ImageWithAlt | null;
      photo: null;
      genres: null;
      format: null;
      maturity: null;
      shortDescription: null;
      excerpt: string | null;
      location: null;
      creatorName: null;
      studioName: null;
    }
  | {
      _type: "creator";
      _id: string;
      title: null;
      name: string;
      slug: string;
      cover: null;
      photo: ImageWithAlt | null;
      genres: Array<
        | "Action & Adventure"
        | "Crime & Noir"
        | "Drama"
        | "Fantasy"
        | "Historical"
        | "Horror"
        | "Humor & Satire"
        | "Memoir & Autobio"
        | "Punk & Protest"
        | "Queer"
        | "Romance"
        | "Sci-Fi"
        | "Slice of Life"
        | "Superhero"
        | "Weird & Experimental"
      > | null;
      format: null;
      maturity: null;
      shortDescription: null;
      excerpt: null;
      location: string | null;
      creatorName: null;
      studioName: string | null;
    }
  | {
      _type: "interview";
      _id: string;
      title: string;
      name: null;
      slug: string;
      cover: ImageWithAlt | null;
      photo: null;
      genres: null;
      format: null;
      maturity: null;
      shortDescription: null;
      excerpt: string | null;
      location: null;
      creatorName: null;
      studioName: null;
    }
> | null;

// Source: src/lib/queries.ts
// Variable: SITEMAP_QUERY
// Query: {  "books": *[_type=="book" && defined(slug.current)]{"slug":slug.current,_updatedAt},  "creators": *[_type=="creator" && defined(slug.current)]{"slug":slug.current,_updatedAt},  "columns": *[_type=="column" && defined(slug.current)]{"slug":slug.current,_updatedAt},  "interviews": *[_type=="interview" && defined(slug.current)]{"slug":slug.current,_updatedAt},  "downloads": *[_type=="freeDownload" && defined(slug.current)]{"slug":slug.current,_updatedAt},  "genres": array::unique(*[_type=="book" && defined(genres)].genres[])}
export type SITEMAP_QUERY_RESULT = {
  books: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  creators: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  columns: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  interviews: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  downloads: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  genres: Array<
    | "Action & Adventure"
    | "Crime & Noir"
    | "Drama"
    | "Fantasy"
    | "Historical"
    | "Horror"
    | "Humor & Satire"
    | "Memoir & Autobio"
    | "Punk & Protest"
    | "Queer"
    | "Romance"
    | "Sci-Fi"
    | "Slice of Life"
    | "Superhero"
    | "Weird & Experimental"
  >;
};

// Source: src/lib/queries.ts
// Variable: GENRE_CREATORS_QUERY
// Query: *[_type=="creator" && $genre in genres]|order(name asc){  _id,name,"slug":slug.current,location,photo,genres,openToCollaboration,  studio->{_id,name,"slug":slug.current,website,logo}}
export type GENRE_CREATORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  location: string | null;
  photo: ImageWithAlt | null;
  genres: Array<
    | "Action & Adventure"
    | "Crime & Noir"
    | "Drama"
    | "Fantasy"
    | "Historical"
    | "Horror"
    | "Humor & Satire"
    | "Memoir & Autobio"
    | "Punk & Protest"
    | "Queer"
    | "Romance"
    | "Sci-Fi"
    | "Slice of Life"
    | "Superhero"
    | "Weird & Experimental"
  > | null;
  openToCollaboration: boolean | null;
  studio: {
    _id: string;
    name: string;
    slug: string;
    website: string | null;
    logo: ImageWithAlt | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type=="creator"]|order(name asc){_id,name,"slug":slug.current,location,photo,genres,openToCollaboration,studio->{_id,name,"slug":slug.current,website,logo}}': CREATORS_QUERY_RESULT;
    '*[_type=="creator" && slug.current==$slug][0]{\n  _id,name,location,website,bio,photo,socials,openToCollaboration,genres,formats,audience,\n  studio->{_id,name,"slug":slug.current,website,logo},\n  organizations[]->{_id,name,"slug":slug.current,website,logo},\n  favoriteCreators[]{name,url,"onSiteName":onSite->name,"onSiteSlug":onSite->slug.current},\n  "books": *[_type=="book" && references(^._id)]|order(title asc){_id,title,"slug":slug.current,status,genres,format,maturity,cover,"creatorName":creator->name}\n}': CREATOR_QUERY_RESULT;
    '*[_type=="book"]|order(title asc){_id,title,"slug":slug.current,status,genres,format,maturity,cover,"creatorName":creator->name}': BOOKS_QUERY_RESULT;
    '*[_type=="book" && slug.current==$slug][0]{\n  _id,title,status,genres,format,maturity,description,buyLinks,kickstarterUrl,cover,\n  "creatorName":creator->name,"creatorSlug":creator->slug.current\n}': BOOK_QUERY_RESULT;
    'array::unique(*[_type=="book" && defined(genres)].genres[])': GENRES_QUERY_RESULT;
    '*[_type=="book" && $genre in genres]|order(title asc){_id,title,"slug":slug.current,status,genres,format,maturity,cover,"creatorName":creator->name}': GENRE_BOOKS_QUERY_RESULT;
    '*[_type=="column"]|order(publishedAt desc){_id,title,"slug":slug.current,excerpt,cover,publishedAt,"authorName":author->name}': COLUMNS_QUERY_RESULT;
    '*[_type=="column" && slug.current==$slug][0]{_id,title,body,publishedAt,cover,"authorName":author->name}': COLUMN_QUERY_RESULT;
    '*[_type=="interview"]|order(publishedAt desc){_id,title,"slug":slug.current,excerpt,cover,publishedAt,"interviewerName":interviewer->name,"subjectName":subject->name}': INTERVIEWS_QUERY_RESULT;
    '*[_type=="interview" && slug.current==$slug][0]{_id,title,body,publishedAt,cover,"interviewerName":interviewer->name,"subjectName":subject->name}': INTERVIEW_QUERY_RESULT;
    '*[_type=="freeDownload"]|order(publishedAt desc){_id,title,"slug":slug.current,description,cover,publishedAt,"creatorName":creator->name}': DOWNLOADS_QUERY_RESULT;
    '*[_type=="freeDownload" && slug.current==$slug][0]{_id,title,description,cover,"creatorName":creator->name,"fileUrl":file.asset->url}': DOWNLOAD_QUERY_RESULT;
    '*[_type=="homepageFeature" && active==true]|order(order asc)[0].items[]->{\n  _type,_id,title,name,"slug":slug.current,cover,photo,genres,format,maturity,\n  shortDescription,excerpt,location,\n  "creatorName":creator->name,\n  "studioName":studio->name\n}': FEATURES_QUERY_RESULT;
    '{\n  "books": *[_type=="book" && defined(slug.current)]{"slug":slug.current,_updatedAt},\n  "creators": *[_type=="creator" && defined(slug.current)]{"slug":slug.current,_updatedAt},\n  "columns": *[_type=="column" && defined(slug.current)]{"slug":slug.current,_updatedAt},\n  "interviews": *[_type=="interview" && defined(slug.current)]{"slug":slug.current,_updatedAt},\n  "downloads": *[_type=="freeDownload" && defined(slug.current)]{"slug":slug.current,_updatedAt},\n  "genres": array::unique(*[_type=="book" && defined(genres)].genres[])\n}': SITEMAP_QUERY_RESULT;
    '*[_type=="creator" && $genre in genres]|order(name asc){\n  _id,name,"slug":slug.current,location,photo,genres,openToCollaboration,\n  studio->{_id,name,"slug":slug.current,website,logo}\n}': GENRE_CREATORS_QUERY_RESULT;
  }
}
